// <auto-generated />
using Gibbon.Git.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gibbon.Git.Server.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteGibbonContext))]
    [Migration("20250930133212_AddPreferredIdeToUserSettings")]
    partial class AddPreferredIdeToUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Gibbon.Git.Server.Data.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AllowAnonymousPush")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AllowAnonymousPush");

                    b.Property<bool>("Anonymous")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Anonymous");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Group")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Group");

                    b.Property<string>("LinksRegex")
                        .HasColumnType("TEXT")
                        .HasColumnName("LinksRegex");

                    b.Property<string>("LinksUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("LinksUrl");

                    b.Property<bool>("LinksUseGlobal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LinksUseGlobal");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Repository", (string)null);
                });

            modelBuilder.Entity("Gibbon.Git.Server.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "System administrator",
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Gibbon.Git.Server.Data.Entities.ServerSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAnonymousPush")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAnonymousRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowUserRepositoryCreation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCommitAuthorAvatarVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinksRegex")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinksUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteCssUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteLogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings", (string)null);
                });

            modelBuilder.Entity("Gibbon.Git.Server.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("Gibbon.Git.Server.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Username")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            GivenName = "admin",
                            Password = "2dpBKPc2rPqPa03udauh6LUo4uNHFSNQZaH4P1BIkNizmUmuir/61Vgkr5MaXlr+bVWnefxQD1H1ciMEtEr/hQ==",
                            PasswordSalt = "/4fKgvYmp7iCSD7JJMPhrw==",
                            Surname = "",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Gibbon.Git.Server.Data.Entities.UserSettingsEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateFormat")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultHomePage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredIde")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredThemeMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("TeamRepository_Permission", b =>
                {
                    b.Property<int>("Repository_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Repository_Id", "Team_Id");

                    b.HasIndex("Team_Id");

                    b.ToTable("TeamRepository_Permission");
                });

            modelBuilder.Entity("UserRepository_Administrator", b =>
                {
                    b.Property<int>("Repository_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Repository_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserRepository_Administrator");
                });

            modelBuilder.Entity("UserRepository_Permission", b =>
                {
                    b.Property<int>("Repository_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Repository_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserRepository_Permission");
                });

            modelBuilder.Entity("UserRole_InRole", b =>
                {
                    b.Property<int>("Role_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Role_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserRole_InRole");

                    b.HasData(
                        new
                        {
                            Role_Id = 1,
                            User_Id = 1
                        });
                });

            modelBuilder.Entity("UserTeam_Member", b =>
                {
                    b.Property<int>("Team_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Team_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserTeam_Member");
                });

            modelBuilder.Entity("TeamRepository_Permission", b =>
                {
                    b.HasOne("Gibbon.Git.Server.Data.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("Repository_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gibbon.Git.Server.Data.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("Team_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRepository_Administrator", b =>
                {
                    b.HasOne("Gibbon.Git.Server.Data.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("Repository_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gibbon.Git.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRepository_Permission", b =>
                {
                    b.HasOne("Gibbon.Git.Server.Data.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("Repository_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gibbon.Git.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRole_InRole", b =>
                {
                    b.HasOne("Gibbon.Git.Server.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gibbon.Git.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTeam_Member", b =>
                {
                    b.HasOne("Gibbon.Git.Server.Data.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("Team_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gibbon.Git.Server.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
