title: Gibbon Git Server
email: m.voigt@code-ix.de
description: >- 
  Bonobo Git Server for Windows is a web application you can install on your IIS. It provides an easy management tool and access to your git repositories that are self hosted on your server.
baseurl: "Gibbon-Git-Server" 
url: "https://code-ix.github.io/Gibbon-Git-Server/"

permalink: /:title.html

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

currentVersion: 1.0.0

defaults:
  - scope:
      path: ""
    values:
      layout: "markdown"
      showInMenu: true
